model_params:
  model: PneumoniaNet
  encoder_name: densenet121
  pretrained: False

args:
  expdir: src
  baselogdir: logs
  verbose: True

stages:
  data_params:
    batch_size: 8
    num_workers: 2

  state_params:
    main_metric: &main_metric accuracy01
    minimize_metric: &minimize_metric False

  criterion_params:
    criterion: CrossEntropyLoss

  optimizer_params:
    optimizer: AdamW
    lr: 0.003
    weight_decay: 0.005

  scheduler_params:
    scheduler: ReduceLROnPlateau
    mode: max
    patience: 3
    factor: 0.75
    verbose: False

  stage1:
    stage_params:
      num_epochs: 3

    callbacks_params:
      loss:
        callback: CriterionCallback

      optimizer:
        callback: OptimizerCallback

      scheduler:
        callback: SchedulerCallback

      accuracy:
        callback: AccuracyCallback

      f1score:
        callback: F1ScoreCallback

      precision:
        callback: PrecisionCallback

      recall:
        callback: RecallCallback

      auc:
        callback: AUCCallback

      tracer:
        callback: TracerCallback
        metric: *main_metric
        minimize: *minimize_metric
        mode: best
