model_params:
  model: PneumoniaNet
  encoder_name: "densenet121"
  pretrained: False

args:
  expdir: src
  baselogdir: logs
  verbose: True

stages:
  data_params:
    batch_size: 32
    num_workers: 4
    path_to_dataset: ./data_pneumonia

  state_params:
    main_metric: &main_metric accuracy01
    minimize_metric: &minimize_metric False

  criterion_params:
    criterion: CrossEntropyLoss

  optimizer_params:
    optimizer: AdamW
    lr: 0.0005
    weight_decay: 0.0

  scheduler_params:
    scheduler: CosineAnnealingWarmRestarts
    T_0: 10
    T_mult: 1
    eta_min: 0.00005
    last_epoch: -1

  stage1:
    stage_params:
      num_epochs: 250

    callbacks_params:
      loss:
        callback: CriterionCallback

      optimizer:
        callback: OptimizerCallback

      scheduler:
        callback: SchedulerCallback

      accuracy:
        callback: AccuracyCallback

      f1score:
        callback: F1ScoreCallback

      precision:
        callback: PrecisionCallback

      recall:
        callback: RecallCallback

      confusion_matrix:
        callback: ConfusionMatrixCallback
        class_names: ['normal', 'pneumonia', 'other']
        num_classes: 3
        tensorboard_callback_name: tensorboard

      tensorboard:
        callback: TensorboardLogger

      tracer:
        callback: TracerCallback
        metric: *main_metric
        minimize: *minimize_metric
        mode: best
